tap "homebrew/cask"
tap "homebrew/services"
tap "homebrew/cask-fonts"

brew "node"
brew "mysql"
brew "yarn"
brew "zsh"
brew "gh"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "zsh-syntax-highlighting"
brew "bash-completion@2"

cask "karabiner-elements"
cask "hammerspoon"
cask "iterm2"
cask "flux"
cask "slack"
cask "alfred"
cask "spotify"
cask "discord"
cask "font-hack-nerd-font"
